version: '2'
services:
  factorio:
    image: ghcr.io/doridian/factorio-docker/factorio:stable
    ports:
     - "34197:34197/udp"
     - "27015:27015/tcp"
    volumes:
     - /opt/factorio:/factorio
#    environment:
#      - PUID=1000
#      - PGID=1000
#      - UPDATE_MODS_ON_START=true
#      - USERNAME=FactorioUsername
#      - TOKEN=FactorioToken
#      - PORT=34197
#      - ADDR=0.0.0.0
