name: Docker build

on:
  schedule:
    - cron: '42 * * * *'
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
      packages: write

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ github.token }}
      - name: Checkout
        uses: actions/checkout@v4
      - name: Expose GitHub Runtime
        uses: crazy-max/ghaction-github-runtime@v3
      - name: Update Docker version
        env:
            DOCKER_CLI_EXPERIMENTAL: enabled
        uses: crazy-max/ghaction-setup-docker@v3
        with:
            channel: stable
            daemon-config: |
                {
                  "features": {
                    "containerd-snapshotter": true
                  }
                }
      - name: Build
        run: |
          ./build.py
        if: ${{ github.event_name == 'pull_request' }}
      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
        if: ${{ github.event_name != 'pull_request' }}
      - name: Build + Push
        run: |
          ./build.py --push-tags
        if: ${{ github.event_name == 'push' }}
      - name: Build + Cron
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ github.token }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: |
          ./build.py --cron --push-tags
        if: ${{ github.event_name == 'schedule' }}
