name: Docker build

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ github.token }}
      - name: Checkout
        uses: actions/checkout@v4
      - name: Update Docker version
        env:
            DOCKER_CLI_EXPERIMENTAL: enabled
        uses: crazy-max/ghaction-setup-docker@v3
        with:
            channel: stable
            daemon-config: |
                {
                  "features": {
                    "containerd-snapshotter": true
                  }
                }
      - name: build
        run: |
          ./build.py
