name: "Factorio version check"

on:
  schedule:
    - cron: '42 * * * *'
  push:
    branches:
      - factorio-auto-up

jobs:
  versioncheck:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
      packages: write
    steps:
      - name: Setup git config
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
      - name: Checkout
        uses: actions/checkout@v3
      - run: ./.github/factorio_version.py
        id: pyscript
      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
        if: ${{ steps.pyscript.outputs.docker == 'true' }}
      - name: build and push
        run: |
          ./build.py --push-tags
        if: ${{ steps.pyscript.outputs.docker == 'true' }}
