name: "Factorio version check"

on:
  schedule:
    - cron: '* * * * *'
  push:
    branches:
      - factorio-auto-up

jobs:
  versioncheck:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
    steps:
      - name: Setup git config
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
      - name: Checkout
        uses: actions/checkout@v2
      - run: ./.github/factorio_version.py
        id: pyscript
    outputs:
      docker: ${{steps.pyscript.outputs.docker}}
  build:
    needs: [versioncheck]
    uses: ./.github/workflows/docker_push.yml
    if: ${{ needs.versioncheck.outputs.docker == "true" }}
