name: "Factorio version check"

on:
  schedule:
    - cron: '30 * * * *'
  push:
    branches:
      - factorio-auto-up

jobs:
  versioncheck:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
    steps:
      - name: Setup git config
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
      - name: Checkout
        uses: actions/checkout@v2
      - run: ./.github/factorio_version.py
