name: "Factorio version check"

on:
  push:
    branches:
      - factorio-auto-up

jobs:
  versioncheck:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: ./.github/factorio_version.py
